language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install nose"
  - "pip install nose-parameterized"
  - "pip install flake8"
  - "pip install coveralls"
before_script:
  - "flake8 --ignore E501 hipy/ *.py"
script:
  - "nosetests -c nose.cfg"
after_script:
  - "coveralls"
notifications:
  email:
    - marthjod@gmail.com
