language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - "python setup.py nosetests"
after_script:
  - "coveralls --verbose"
notifications:
  email:
    - marthjod@gmail.com
