#!/usr/bin/env python

import sys

import click

from hipy import __version__
from hipy.parser import HieraOutputParser


@click.command()
@click.version_option(version=__version__)
@click.option('--json/--python', help='Format output as JSON/Python (default: JSON)', default=True)
def convert(json):
    """Convert Hiera output to JSON/Python"""

    inp = sys.stdin.read().strip()
    parser = HieraOutputParser(text=inp, debug=debug)

    if not json:
        print(parser.get_python())
    else:
        print(parser.get_json())


if __name__ == "__main__":
    convert()
